name = "1003-site-worker"
account_id = "1b47c0ee9640c245ba237fa508e0178b"
workers_dev = false
compatibility_date = "2025-03-28"

main = "worker.js"

[assets]
directory = "./public"
binding = "www-as1003-net-ASSETS"
not_found_handling = "404-page"
